server:
  port: 80

spring:
  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.com:7001/eureka
      #defaultZone: http://eureka.com:7001/eureka,http://eureka.com:7002/eureka
  instance:
    #如果prefer-ip-address=true则优先使用ip调用该微服务，如果prefer-ip-address=false则优先使用hostname调用
    prefer-ip-address: true
    hostname: order.com
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    instance-id: ${spring.application.name}:${server.port}
    #Eureka客户端向服务端发送心跳的时间间隔。默认30秒
    lease-renewal-interval-in-seconds: 3
    #Eureka服务端最后一次接收到客户端心跳后等待的时间上线，超时踢出该实例。默认90秒
    lease-expiration-duration-in-seconds: 5