server:
  port: 80

spring:
  application:
    name: orderzk-service
  cloud:
    zookeeper:
      connect-string: 192.168.199.116:2181
      discovery:
        #每个服务在zookeeper创建的均为临时节点。这里不配置默认zookeeper的节点名是uuid
        instance-id: payment-${server.port}