server:
  port: 7002

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #单实例情况defaultZone为自身，多实例情况defaultZone为集群其他的eurekaServer地址
      #defaultZone: http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: eureka7002.com
  server:
    #关闭自我保护机制，使不可用服务及时踢出
    enable-self-preservation: false
    #清除过期实例时间间隔，默认60毫秒
    eviction-interval-timer-in-ms: 2000
