server:
  port: 7001

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #单实例情况defaultZone为自身，多实例情况defaultZone为集群其他的eurekaServer地址，多个地址逗号隔开
      defaultZone: http://eureka.com:7001/eureka
      #defaultZone: http://eureka.com:7002/eureka
  instance:
    hostname: eureka.com
  server:
    #关闭自我保护机制，使不可用服务及时踢出
    enable-self-preservation: false
    #清除过期实例时间间隔，默认60毫秒
    eviction-interval-timer-in-ms: 2000